const countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
    "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the",
    "Congo, Republic of the", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
    "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
    "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "North Korea", "South Korea", "Kosovo",
    "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
    "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea",
    "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
    "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka",
    "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago",
    "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay",
    "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

const regionData = {
    "United States": {
        "Alabama": ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
        "Alaska": ["Anchorage", "Juneau", "Fairbanks", "Wasilla", "Sitka"],
        "Arizona": ["Phoenix", "Tucson", "Mesa", "Chandler", "Glendale"],
        "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
        "California": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento"],
        "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
        "Connecticut": ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
        "Delaware": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
        "Florida": ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee"],
        "Georgia": ["Atlanta", "Augusta", "Savannah", "Columbus", "Macon"],
        "Hawaii": ["Honolulu", "Hilo", "Kailua", "Kapolei", "Kaneohe"],
        "Idaho": ["Boise", "Idaho Falls", "Meridian", "Nampa", "Pocatello"],
        "Illinois": ["Chicago", "Springfield", "Aurora", "Naperville", "Joliet"],
        "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
        "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
        "Kansas": ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
        "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
        "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
        "Maine": ["Portland", "Bangor", "Augusta", "Lewiston", "Auburn"],
        "Maryland": ["Baltimore", "Annapolis", "Frederick", "Rockville", "Gaithersburg"],
        "Massachusetts": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
        "Michigan": ["Detroit", "Grand Rapids", "Lansing", "Ann Arbor", "Flint"],
        "Minnesota": ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
        "Mississippi": ["Jackson", "Gulfport", "Hattiesburg", "Biloxi", "Meridian"],
        "Missouri": ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
        "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
        "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
        "Nevada": ["Las Vegas", "Reno", "Henderson", "North Las Vegas", "Sparks"],
        "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry", "Rochester"],
        "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison"],
        "New Mexico": ["Albuquerque", "Santa Fe", "Las Cruces", "Roswell", "Farmington"],
        "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse"],
        "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
        "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
        "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
        "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton"],
        "Oregon": ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro"],
        "Pennsylvania": ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown", "Erie"],
        "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence"],
        "South Carolina": ["Charleston", "Columbia", "Greenville", "Myrtle Beach", "Spartanburg"],
        "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
        "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
        "Texas": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
        "Utah": ["Salt Lake City", "Provo", "West Valley City", "Orem", "Sandy"],
        "Vermont": ["Burlington", "Montpelier", "Rutland", "South Burlington", "Barre"],
        "Virginia": ["Virginia Beach", "Richmond", "Norfolk", "Chesapeake", "Arlington"],
        "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
        "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
        "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
        "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"]
    },
    "Canada": {
        "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "St. Albert"],
        "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Richmond"],
        "Manitoba": ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"],
        "New Brunswick": ["Fredericton", "Moncton", "Saint John", "Bathurst", "Miramichi"],
        "Newfoundland and Labrador": ["St. John's", "Corner Brook", "Mount Pearl", "Gander", "Grand Falls-Windsor"],
        "Nova Scotia": ["Halifax", "Sydney", "Dartmouth", "Truro", "New Glasgow"],
        "Ontario": ["Toronto", "Ottawa", "Hamilton", "Mississauga", "London"],
        "Prince Edward Island": ["Charlottetown", "Summerside", "Stratford", "Cornwall", "Montague"],
        "Quebec": ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"],
        "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current"]
    },
    "Brazil": {
        "Acre": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó"],
        "Alagoas": ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo", "Penedo"],
        "Amapá": ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Mazagão"],
        "Amazonas": ["Manaus", "Parintins", "Itacoatiara", "Tefé", "Coari"],
        "Bahia": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna"],
        "Ceará": ["Fortaleza", "Juazeiro do Norte", "Sobral", "Caucaia", "Maracanaú"],
        "Distrito Federal": ["Brasília", "Taguatinga", "Ceilândia", "Gama", "Planaltina"],
        "Espírito Santo": ["Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares"],
        "Goiás": ["Goiânia", "Anápolis", "Aparecida de Goiânia", "Rio Verde", "Luziânia"],
        "Maranhão": ["São Luís", "Imperatriz", "Caxias", "Timon", "Codó"],
        "Mato Grosso": ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra"],
        "Mato Grosso do Sul": ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã"],
        "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim"],
        "Pará": ["Belém", "Santarém", "Marabá", "Ananindeua", "Altamira"],
        "Paraíba": ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux"],
        "Paraná": ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel"],
        "Pernambuco": ["Recife", "Olinda", "Caruaru", "Jaboatão dos Guararapes", "Petrolina"],
        "Piauí": ["Teresina", "Parnaíba", "Picos", "Floriano", "Piripiri"],
        "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Petrópolis", "Campos dos Goytacazes", "Volta Redonda"],
        "Rio Grande do Norte": ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Macaíba"],
        "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas", "Santa Maria", "Canoas"],
        "Rondônia": ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal"],
        "Roraima": ["Boa Vista", "Rorainópolis", "Caracaraí", "Alto Alegre", "Mucajaí"],
        "Santa Catarina": ["Florianópolis", "Joinville", "Blumenau", "São José", "Criciúma"],
        "São Paulo": ["São Paulo", "Campinas", "Santos", "São José dos Campos", "Ribeirão Preto"],
        "Sergipe": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "Estância"]
    },
    "Germany": {
        "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Würzburg"],
        "Berlin": ["Berlin"],
        "Baden-Württemberg": ["Stuttgart", "Karlsruhe", "Mannheim", "Freiburg", "Heidelberg"],
        "Brandenburg": ["Potsdam", "Cottbus", "Brandenburg an der Havel", "Frankfurt (Oder)", "Oranienburg"],
        "Bremen": ["Bremen"],
        "Hamburg": ["Hamburg"],
        "Hesse": ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"],
        "Lower Saxony": ["Hanover", "Braunschweig", "Oldenburg", "Osnabrück", "Wolfsburg"],
        "Mecklenburg-Vorpommern": ["Schwerin", "Rostock", "Neubrandenburg", "Stralsund", "Greifswald"],
        "North Rhine-Westphalia": ["Düsseldorf", "Cologne", "Dortmund", "Essen", "Duisburg"],
        "Rhineland-Palatinate": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern"],
        "Saarland": ["Saarbrücken", "Neunkirchen", "Homburg", "Völklingen", "Sankt Ingbert"],
        "Saxony": ["Dresden", "Leipzig", "Chemnitz", "Zwickau", "Plauen"],
        "Saxony-Anhalt": ["Magdeburg", "Halle", "Dessau", "Wittenberg", "Weißenfels"],
        "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg", "Neumünster", "Norderstedt"],
        "Thuringia": ["Erfurt", "Weimar", "Jena", "Gera", "Eisenach"]
    },
    "India": {
        "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati"],
        "Arunachal Pradesh": ["Itanagar", "Pasighat", "Tawang", "Ziro", "Bomdila"],
        "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
        "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"],
        "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
        "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
        "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
        "Haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala", "Yamunanagar"],
        "Himachal Pradesh": ["Shimla", "Dharamshala", "Manali", "Solan", "Mandi"],
        "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar"],
        "Karnataka": ["Bangalore", "Mysore", "Mangalore", "Hubli-Dharwad", "Belgaum"],
        "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
        "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"],
        "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
        "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul"],
        "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin", "Baghmara"],
        "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib"],
        "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"],
        "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Balasore"],
        "Punjab": ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala"],
        "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner"],
        "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Ravangla"],
        "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
        "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Kukatpally", "Gachibowli", "Uppal", "Ameerpet", "Kokapet",
            "Hi-tech city", "Madhapur", "Jubliee Hills", "Banjara Hills", "Medhipatnam", "Secunderabad", "Dilsukhnagar", "Tarnaka"],
        "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Belonia"],
        "Uttar Pradesh": ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut"],
        "Uttarakhand": ["Dehradun", "Haridwar", "Nainital", "Roorkee", "Haldwani"],
        "West Bengal": ["Kolkata", "Howrah", "Darjeeling", "Siliguri", "Durgapur"]
    },
    "Japan": {
        "Aichi": ["Nagoya", "Toyota", "Okazaki", "Toyohashi", "Seto"],
        "Akita": ["Akita", "Yokote", "Oga", "Noshiro", "Odate"],
        "Aomori": ["Aomori", "Hirosaki", "Hachinohe", "Goshogawara", "Mutsu"],
        "Chiba": ["Chiba", "Funabashi", "Matsudo", "Ichikawa", "Narita"],
        "Ehime": ["Matsuyama", "Imabari", "Niihama", "Saijo", "Uwajima"],
        "Fukui": ["Fukui", "Sakai", "Tsuruga", "Obama", "Katsuyama"],
        "Fukuoka": ["Fukuoka", "Kitakyushu", "Kurume", "Omuta", "Iizuka"],
        "Fukushima": ["Fukushima", "Koriyama", "Iwaki", "Aizuwakamatsu", "Shirakawa"],
        "Gifu": ["Gifu", "Ogaki", "Kakamigahara", "Tajimi", "Takayama"],
        "Gunma": ["Maebashi", "Takasaki", "Ota", "Isesaki", "Kiryu"],
        "Hiroshima": ["Hiroshima", "Kure", "Fukuyama", "Onomichi", "Mihara"],
        "Hokkaido": ["Sapporo", "Hakodate", "Asahikawa", "Obihiro", "Kitami"],
        "Hyogo": ["Kobe", "Himeji", "Amagasaki", "Nishinomiya", "Akashi"],
        "Ibaraki": ["Mito", "Tsukuba", "Hitachi", "Tsuchiura", "Kashima"],
        "Ishikawa": ["Kanazawa", "Komatsu", "Nanao", "Kaga", "Suzu"],
        "Iwate": ["Morioka", "Ichinoseki", "Miyako", "Oshu", "Hanamaki"],
        "Kagawa": ["Takamatsu", "Marugame", "Sakaide", "Zentsuji", "Mitoyo"],
        "Kagoshima": ["Kagoshima", "Kanoya", "Ibusuki", "Izumi", "Akune"],
        "Kanagawa": ["Yokohama", "Kawasaki", "Sagamihara", "Yokosuka", "Fujisawa"],
        "Kochi": ["Kochi", "Nankoku", "Sukumo", "Shimanto", "Tosa"],
        "Kumamoto": ["Kumamoto", "Yatsushiro", "Amakusa", "Arao", "Tamana"],
        "Kyoto": ["Kyoto", "Uji", "Kameoka", "Maizuru", "Fukuchiyama"],
        "Mie": ["Tsu", "Yokkaichi", "Suzuka", "Matsusaka", "Ise"],
        "Miyagi": ["Sendai", "Ishinomaki", "Osaki", "Shiogama", "Kesennuma"],
        "Miyazaki": ["Miyazaki", "Nichinan", "Hyuga", "Nobeoka", "Kobayashi"],
        "Nagano": ["Nagano", "Matsumoto", "Ueda", "Suwa", "Iida"],
        "Nagasaki": ["Nagasaki", "Sasebo", "Shimabara", "Omura", "Matsuura"],
        "Nara": ["Nara", "Yamatokoriyama", "Kashihara", "Ikoma", "Sakurai"],
        "Niigata": ["Niigata", "Nagaoka", "Joetsu", "Sanjo", "Shibata"],
        "Oita": ["Oita", "Beppu", "Nakatsu", "Usuki", "Tsukumi"],
        "Okayama": ["Okayama", "Kurashiki", "Tsuyama", "Sanyo-Onoda", "Takahashi"],
        "Okinawa": ["Naha", "Okinawa City", "Urasoe", "Ginowan", "Itoman"],
        "Osaka": ["Osaka", "Sakai", "Higashiosaka", "Toyonaka", "Takatsuki"],
        "Saga": ["Saga", "Karatsu", "Tosu", "Imari", "Takeo"],
        "Saitama": ["Saitama", "Kawaguchi", "Koshigaya", "Tokorozawa", "Kawagoe"],
        "Shiga": ["Otsu", "Hikone", "Kusatsu", "Nagahama", "Moriyama"],
        "Shimane": ["Matsue", "Izumo", "Hamada", "Masuda", "Yasugi"],
        "Shizuoka": ["Shizuoka", "Hamamatsu", "Numazu", "Fujieda", "Izu"],
        "Tochigi": ["Utsunomiya", "Ashikaga", "Tochigi", "Sano", "Kanuma"],
        "Tokushima": ["Tokushima", "Naruto", "Anan", "Komatsushima", "Yoshinogawa"],
        "Tokyo": ["Tokyo", "Hachioji", "Machida", "Chuo", "Shinjuku"],
        "Tottori": ["Tottori", "Yonago", "Kurayoshi", "Sakaiminato", "Wakasa"],
        "Toyama": ["Toyama", "Takaoka", "Uozu", "Namerikawa", "Himi"],
        "Wakayama": ["Wakayama", "Tanabe", "Kainan", "Hashimoto", "Kinokawa"],
        "Yamagata": ["Yamagata", "Tsuruoka", "Sakata", "Yonezawa", "Obanazawa"],
        "Yamaguchi": ["Shimonoseki", "Ube", "Yamaguchi", "Hofu", "Hagi"],
        "Yamanashi": ["Kofu", "Fujiyoshida", "Minami-Alps", "Nirasaki", "Yamanashi"]
    },
    "North Korea": {
        "Pyongyang": ["Pyongyang"],
        "Hamgyong": ["Hamhung", "Chongjin", "Kimchaek", "Hyesan", "Sinuiju"],
        "Hwanghae": ["Haeju", "Sariwon", "Songnim", "Sinchon", "Unpa"],
        "Kangwon": ["Wonsan", "Munchon", "Kowon", "Kimhwa", "Sepho"],
        "North Pyongan": ["Sinuiju", "Chongju", "Sonchon", "Sakchu", "Ryongchon"],
        "South Pyongan": ["Pyongsong", "Anju", "Kaechon", "Songchon", "Sunchon"],
        "Ryanggang": ["Hyesan", "Kimjongsuk", "Samsu", "Pochon", "Unhung"],
        "Chagang": ["Kanggye", "Huichon", "Manpo", "Huchang", "Rangrim"]
    },
    "South Korea": {
        "Seoul": ["Seoul", "Jongno-gu", "Gangnam-gu", "Jung-gu", "Songpa-gu"],
        "Busan": ["Busan", "Haeundae-gu", "Suyeong-gu", "Sasang-gu", "Dongnae-gu"],
        "Incheon": ["Incheon", "Namdong-gu", "Bupyeong-gu", "Yeonsu-gu", "Jung-gu"],
        "Daegu": ["Daegu", "Dalseo-gu", "Suseong-gu", "Nam-gu", "Buk-gu"],
        "Daejeon": ["Daejeon", "Yuseong-gu", "Seo-gu", "Dong-gu", "Jung-gu"],
        "Gwangju": ["Gwangju", "Buk-gu", "Seo-gu", "Dong-gu", "Nam-gu"],
        "Ulsan": ["Ulsan", "Nam-gu", "Buk-gu", "Dong-gu", "Jung-gu"],
        "Gyeonggi": ["Suwon", "Goyang", "Yongin", "Seongnam", "Bucheon"],
        "Gangwon": ["Chuncheon", "Gangneung", "Wonju", "Sokcho", "Samcheok"],
        "North Chungcheong": ["Cheongju", "Chungju", "Jecheon", "Eumseong", "Danyang"],
        "South Chungcheong": ["Daejeon", "Cheonan", "Asan", "Seosan", "Dangjin"],
        "North Jeolla": ["Jeonju", "Gunsan", "Iksan", "Jeongeup", "Namwon"],
        "South Jeolla": ["Gwangju", "Yeosu", "Suncheon", "Mokpo", "Naju"],
        "North Gyeongsang": ["Daegu", "Pohang", "Gumi", "Gyeongju", "Andong"],
        "South Gyeongsang": ["Busan", "Changwon", "Jinju", "Yangsan", "Miryang"],
        "Jeju": ["Jeju City", "Seogwipo", "Seongsan", "Hallim", "Jocheon"]
    },
    "Mexico": {
        "Aguascalientes": ["Aguascalientes", "Calvillo", "Rincón de Romos", "Jesús María", "San Francisco de los Romo"],
        "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Rosarito"],
        "Baja California Sur": ["La Paz", "Cabo San Lucas", "San José del Cabo", "Loreto", "Ciudad Constitución"],
        "Campeche": ["Campeche", "Ciudad del Carmen", "Champotón", "Escárcega", "Calkiní"],
        "Chiapas": ["Tuxtla Gutiérrez", "San Cristóbal de las Casas", "Tapachula", "Comitán", "Palenque"],
        "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias", "Parral", "Cuauhtémoc"],
        "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Ciudad Acuña"],
        "Colima": ["Colima", "Manzanillo", "Tecomán", "Villa de Álvarez", "Comala"],
        "Durango": ["Durango", "Gómez Palacio", "Lerdo", "Ciudad Lerdo", "Santiago Papasquiaro"],
        "Guanajuato": ["León", "Guanajuato", "Irapuato", "Celaya", "Salamanca"],
        "Guerrero": ["Acapulco", "Chilpancingo", "Iguala", "Taxco", "Zihuatanejo"],
        "Hidalgo": ["Pachuca", "Tulancingo", "Tula", "Ixmiquilpan", "Tepeji"],
        "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta"],
        "Mexico City": ["Mexico City"],
        "Michoacán": ["Morelia", "Uruapan", "Zamora", "La Piedad", "Lázaro Cárdenas"],
        "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Jojutla"],
        "Nayarit": ["Tepic", "Bahía de Banderas", "Compostela", "Santiago Ixcuintla", "Acaponeta"],
        "Nuevo León": ["Monterrey", "San Nicolás", "Guadalupe", "Apodaca", "Santa Catarina"],
        "Oaxaca": ["Oaxaca City", "Salina Cruz", "Juchitán", "San Juan Bautista Tuxtepec", "Puerto Escondido"],
        "Puebla": ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "Cholula"],
        "Querétaro": ["Querétaro", "San Juan del Río", "El Marqués", "Corregidora", "Tequisquiapan"],
        "Quintana Roo": ["Cancún", "Chetumal", "Playa del Carmen", "Cozumel", "Tulum"],
        "San Luis Potosí": ["San Luis Potosí", "Soledad", "Matehuala", "Ciudad Valles", "Rioverde"],
        "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis", "Guasave", "Navolato"],
        "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "Guaymas", "Navojoa"],
        "Tabasco": ["Villahermosa", "Teapa", "Cárdenas", "Comalcalco", "Macuspana"],
        "Tamaulipas": ["Tampico", "Reynosa", "Matamoros", "Nuevo Laredo", "Ciudad Victoria"],
        "Tlaxcala": ["Tlaxcala City", "Apizaco", "Huamantla", "San Pablo del Monte", "Chiautempan"],
        "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Poza Rica", "Orizaba"],
        "Yucatán": ["Mérida", "Valladolid", "Tizimín", "Progreso", "Tekax"],
        "Zacatecas": ["Zacatecas City", "Guadalupe", "Fresnillo", "Jerez", "Sombrerete"]
    },
    "Spain": {
        "Andalusia": ["Seville", "Malaga", "Granada", "Cordoba", "Cadiz"],
        "Aragon": ["Zaragoza", "Huesca", "Teruel", "Calatayud", "Utebo"],
        "Asturias": ["Oviedo", "Gijón", "Avilés", "Mieres", "Langreo"],
        "Balearic Islands": ["Palma", "Ibiza", "Mahon", "Inca", "Manacor"],
        "Basque Country": ["Bilbao", "San Sebastián", "Vitoria-Gasteiz", "Barakaldo", "Getxo"],
        "Canary Islands": ["Las Palmas", "Santa Cruz de Tenerife", "La Laguna", "Arrecife", "San Bartolome de Tirajana"],
        "Cantabria": ["Santander", "Torrelavega", "Castro Urdiales", "Camargo", "El Astillero"],
        "Castile and León": ["Valladolid", "Salamanca", "León", "Burgos", "Segovia"],
        "Castile-La Mancha": ["Toledo", "Albacete", "Ciudad Real", "Guadalajara", "Cuenca"],
        "Catalonia": ["Barcelona", "Tarragona", "Lleida", "Girona", "Reus"],
        "Extremadura": ["Mérida", "Badajoz", "Cáceres", "Plasencia", "Don Benito"],
        "Galicia": ["Santiago de Compostela", "A Coruña", "Vigo", "Lugo", "Ourense"],
        "La Rioja": ["Logroño", "Calahorra", "Arnedo", "Haro", "Alfaro"],
        "Madrid": ["Madrid", "Alcala de Henares", "Getafe", "Leganes", "Alcobendas"],
        "Murcia": ["Murcia", "Cartagena", "Lorca", "Molina de Segura", "Yecla"],
        "Navarre": ["Pamplona", "Tudela", "Burlada", "Estella", "Sangüesa"],
        "Valencian Community": ["Valencia", "Alicante", "Castellón", "Elche", "Torrevieja"]
    },
    "United Kingdom": {
        "England": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds"],
        "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry", "Armagh"],
        "Scotland": ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Stirling"],
        "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry"]
    }
};


const countryFormats = {
    'Brazil': {
        'format': '{name},{company} {addressLine1}, {neighborhood}, {city}-{region}, {postalCode}, {country}',
        'labels': {
            'name': 'Name',
            'company': 'Company (optional)',
            'addressLine1': 'Street name and Building number',
            //'addressLine2': 'Apt/Suite',
            'neighborhood': 'Neighborhood (optional)',
            'region': 'State',
            'postalCode': 'Postal code',
            'country': 'Country'
        },
        'postalCodeFormat': '#####-###'
    },
    'Canada': {
        'format': '{name},{company} {addressLine1} {addressLine2} {city} {region} {postalCode} {country}',
        'labels': {
            'name': 'Name',
            'company': 'Company (optional)',
            'addressLine1': 'Unit Number (optional)',
            'addressLine2': 'Street',
            'city': 'City',
            'region': 'Province',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': 'A#A #A#'
    },
    'Germany': {
        'format': '{salutation} {name}, {company}, {addressLine1} {postalCode} {city} {country}',
        'labels': {
            'salutation': 'Salutation',
            'name': 'Name',
            'company': 'Institution / Company name (optional)',
            'addressLine1': 'Street Address / PO Box',
            'region': 'State',
            'postalCode': 'Postal Code',
            'city': 'City/Town',
            'country': 'Country'
        },
        'postalCodeFormat': '#####'
    },
    'India': {
        'format': '{salutation} {name} {company}, {addressLine1}, {locality}, {city}, {region}, {postalCode} {country}',
        'labels': {
            'salutation': 'Salutation',
            'company': 'Company (optional)',
            'name': 'Name',
            'addressLine1': 'Address',
            'locality': 'Landmark (optional)',
            'city': 'City/Town/District',
            'region': 'State',
            'postalCode': 'Pincode',
            'country': 'Country'
        },
        'postalCodeFormat': '######'
    },
   /* Assuming addresses are written in English*/
    'Japan': {
        'format': '{salutation} {company} {name}, {addressLine1}, {addressLine2}, {city}, {region}, {postalCode}, {country}',
        'labels': {
            'salutation': 'Salutation',
            'company': 'Company (optional)',
            'name': 'Name',
            'region': 'Prefecture',
            'city': 'Town/City/District',
            'addressLine1': 'Building, Apt Number',
            'addressLine2': 'Street/Block',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': '###-####'
    },
    'North Korea': {
        'format': '{name}, {addressLine1}, {addressLine2}, {city}, {region}, {postalCode}, {country}',
        'labels': {
            'name': 'Name',
            'addressLine1': 'Address',
            'addressLine2': 'Locality (optional)',
            'city': 'City',
            'region': 'Province',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': '#####'
    },
    'South Korea': {
        'format': '{name}, {addressLine1}, {locality}, {city}, {region}, {postalCode} {country}',
        'labels': {
            'name': 'Name',
            'addressLine1': 'Address',
            'locality': 'Landmark (optional)',
            'city': 'City',
            'region': 'Province',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': '#####'
    },
    'Mexico': {
        'format': '{name}, {addressLine1}, {neighborhood},{postalCode}, {city}, {region}, {country}',
        'labels': {
            'name': 'Name',
            'addressLine1': 'Address',
            'neighborhood': 'Neighborhood',
            'city': 'City',
            'region': 'State',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': '#####'
    },
    'Spain': {
        'format': '{name},{company} {addressLine1}, {addressLine2}, {postalCode}, {city}, {region}, {country}',
        'labels': {
            'name': 'Name',
            'company': 'Company (optional)',
            'addressLine1': 'Address',
            'addressLine2': 'Apt/Building',
            'city': 'City',
            'region': 'Region',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': '#####'
    },
    'United Kingdom': {
        'format': '{name},{company} {addressLine1}, {city} {region}, {postalCode}, {country}',
        'labels': {
            'name': 'Name',
            'company': 'Company (Optional)',
            'addressLine1': 'Address',
            'city': 'City',
            'region': 'Region',
            'postalCode': 'Postal Code',
            'country': 'Country'
        },
        'postalCodeFormat': 'AA#A #AA'
    },
    'United States': {
        'format': '{name}, {company}, {addressLine2}, {addressLine1}, {city}, {region}, {postalCode}, {country}',
        'labels': {
            'name': 'Name',
            'company': 'Company',
            'addressLine1': 'Street/Ave',
            'addressLine2': 'Apt/Suite',
            'city': 'City',
            'region': 'State',
            'postalCode': 'ZIP Code'
        },
        'postalCodeFormat': '#####'
    },
};

module.exports = {
    countries,
    regionData,
    countryFormats,
}